language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - "composer update"

script:
 - ./vendor/bin/phpunit ./tests
 - ./vendor/bin/phpcs --standard=./build/phpcs.xml -n -a ./src/

matrix:
  allow_failures:
     - php: hhvm

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fabefb9ed90dec2c2a94
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

